# Generated by Django 4.1 on 2022-09-13 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_post_kryesore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kryesore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_bannner')),
                ('title', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='kryesore',
        ),
    ]
