# Generated by Django 4.1 on 2022-09-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_kryesore_remove_post_kryesore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kryesore',
            new_name='Kryesoret',
        ),
    ]
