# Generated by Django 4.1 on 2022-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0009_rename_kryesore_kryesoret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kryesoret',
            name='image',
            field=models.ImageField(upload_to='news_kryesoret/'),
        ),
    ]
