# Generated by Django 4.1.1 on 2022-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0011_rename_title_kryesoret_titull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kryesoret',
            name='image',
            field=models.ImageField(upload_to='media/news_kryesoret'),
        ),
    ]
